/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Cells extends javax.swing.JFrame {

    /**
     * Creates new form Cells
     */
    public Cells() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cellid = new javax.swing.JTextField();
        wing = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        high = new javax.swing.JRadioButton();
        mid = new javax.swing.JRadioButton();
        low = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        level1 = new javax.swing.JRadioButton();
        level2 = new javax.swing.JRadioButton();
        level3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    CELLS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 96, 53));

        cellid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cellid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellidActionPerformed(evt);
            }
        });
        jPanel1.add(cellid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, -1));

        wing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wingActionPerformed(evt);
            }
        });
        jPanel1.add(wing, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 160, -1));

        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CELL ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 106, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CELL WING");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 106, 37));

        level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("CELL LEVEL");
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 106, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CELL NUMBER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 106, 38));

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("CELL TYPE");
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 106, 33));

        high.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(high);
        high.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        high.setForeground(new java.awt.Color(255, 255, 255));
        high.setText("HIGH");
        jPanel1.add(high, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        mid.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(mid);
        mid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mid.setForeground(new java.awt.Color(255, 255, 255));
        mid.setText("MID");
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        jPanel1.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        low.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(low);
        low.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        low.setForeground(new java.awt.Color(255, 255, 255));
        low.setText("LOW");
        low.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowActionPerformed(evt);
            }
        });
        jPanel1.add(low, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 107, 46));

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 112, 46));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 97, 50));

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 523, 110, 50));

        level1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(level1);
        level1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level1.setForeground(new java.awt.Color(255, 255, 255));
        level1.setText("LEVEL 1");
        level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ActionPerformed(evt);
            }
        });
        jPanel1.add(level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 275, -1, -1));

        level2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(level2);
        level2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level2.setForeground(new java.awt.Color(255, 255, 255));
        level2.setText("LEVEL 2");
        jPanel1.add(level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 275, -1, -1));

        level3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(level3);
        level3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level3.setForeground(new java.awt.Color(255, 255, 255));
        level3.setText("LEVEL 3");
        jPanel1.add(level3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 275, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p4.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellidActionPerformed

    private void wingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wingActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        cellid.setText("");
        wing.setText("");
       
       number.setText("");
       buttonGroup1.clearSelection();
       buttonGroup2.clearSelection();
        
    }//GEN-LAST:event_clearActionPerformed

    private void lowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(cellid.getText().trim().isEmpty() && wing.getText().trim().isEmpty() && level.getText().trim().isEmpty() && number.getText().trim().isEmpty() && type.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }else if(cellid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if( wing.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(level.getText().trim().isEmpty())
        {
            level=null;
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(number.getText().trim().isEmpty())
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(type.getText().trim().isEmpty())
        {
            type=null;
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            
            String sql="insert into cells values(?,?,?,?,?)";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(1,cellid.getText());
             pstmt.setString(2, wing.getText());
             String level=null;
              if(level1.isSelected())
             {
                 level=level1.getText();
             }
             if(level2.isSelected())
             {
                 level=level2.getText();
             }
             if(level3.isSelected())
             {
                 level=level3.getText();
             }
             pstmt.setString(3,level);
             
             pstmt.setString(4,number.getText());
             String type=null;
             if(high.isSelected())
             {
                 type=high.getText();
             }
             if(mid.isSelected())
             {
                 type=mid.getText();
             }
             if(low.isSelected())
             {
                 type=low.getText();
             }
             pstmt.setString(5,type);
             pstmt.executeUpdate();
              
             JOptionPane.showMessageDialog(null, "Insertion Successfull");
             conn.close();
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Duplicate Entry");
            
        }
    }//GEN-LAST:event_saveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        NextPage np=new NextPage();
                 np.setVisible(true);
                 np.pack();
                 np.setLocationRelativeTo(null);
                 np.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cellsn c=new Cellsn();
        c.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cells().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField cellid;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton high;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel level;
    private javax.swing.JRadioButton level1;
    private javax.swing.JRadioButton level2;
    private javax.swing.JRadioButton level3;
    private javax.swing.JRadioButton low;
    private javax.swing.JRadioButton mid;
    private javax.swing.JTextField number;
    private javax.swing.JButton save;
    private javax.swing.JLabel type;
    private javax.swing.JTextField wing;
    // End of variables declaration//GEN-END:variables
}
