/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Cellup extends javax.swing.JFrame {

    /**
     * Creates new form Cellup
     */
    public Cellup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cellid = new javax.swing.JTextField();
        cellwing = new javax.swing.JTextField();
        cellnumber = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        level = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CELL ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 109, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CELL WING");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 177, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CELL LEVEL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 254, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CELL NUMBER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 328, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CELLS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 70, -1));

        cellid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellidActionPerformed(evt);
            }
        });
        jPanel1.add(cellid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 109, 169, -1));
        jPanel1.add(cellwing, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 169, -1));
        jPanel1.add(cellnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 318, 170, 30));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 100, 50));

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 100, 50));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CELL TYPE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 402, -1, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 100, 45));

        level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "LEVEL 1", "LEVEL 2", "LEVEL 3", " " }));
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 254, 170, -1));

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HIGH", "MID", "LOW" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 402, 170, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p30.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellidActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(cellid.getText().trim().isEmpty() && level.getSelectedItem()=="SELECT" && cellnumber.getText().trim().isEmpty() && type.getSelectedItem()=="SELECT")
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(level.getSelectedItem()=="SELECT"){
            
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(cellnumber.getText().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(type.getSelectedItem()=="SELECT"){
            
            JOptionPane.showMessageDialog(null, "Empty");
        }
          else  
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql="Update cells set Cell_Wing=?,Cell_Level=?,Cell_Number=?,Cell_Type=? where Cell_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setString(1, cellwing.getText());
            if(level.getSelectedItem()=="SELECT")
            {
                level=null;
            }
            if(level.getSelectedItem()=="LEVEL 1")
            {
               level.getSelectedItem();
            }
            if(level.getSelectedItem()=="LEVEL 2")
            {
               level.getSelectedItem();
            }
            if(level.getSelectedItem()=="LEVEL 3")
            {
               level.getSelectedItem();
            }
            
            
            pstmt.setString(2,level.getSelectedItem().toString());
             
              pstmt.setString(3,cellnumber.getText());
             if(type.getSelectedItem()=="SELECT")
            {
                type=null;
            }
            if(type.getSelectedItem()=="HIGH")
            {
               type.getSelectedItem();
            }
            if(type.getSelectedItem()=="MID")
            {
               type.getSelectedItem();
            }
            if(type.getSelectedItem()=="LOW")
            {
               type.getSelectedItem();
            }
           
            
            pstmt.setString(4,type.getSelectedItem().toString());
             pstmt.setString(5,cellid.getText());
             pstmt.executeUpdate();
             
             
                 JOptionPane.showMessageDialog(null,"Update Successful","Cells",JOptionPane.PLAIN_MESSAGE);
             
            
             conn.close();
            
            
            
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         cellid.setText("");
        cellwing.setText("");
       level.setSelectedIndex(0);
        cellnumber.setText("");
        type.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Cellsn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(cellid.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Empty");
        }
        else
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql= "select * from cells where Cell_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,cellid.getText());
            ResultSet rs= pstmt.executeQuery();
            
            if(rs.next())
            {
                cellwing.setText(rs.getString("Cell_Wing"));
                 level.setSelectedItem(rs.getString("Cell_Level"));
                  cellnumber.setText(rs.getString("Cell_Number"));
                    type.setSelectedItem(rs.getString("Cell_Type"));
                
            
                
                
            }else{
                JOptionPane.showMessageDialog(null,"Record not Found");
            }
            conn.close();
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cellup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cellup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cellup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cellup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cellup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cellid;
    private javax.swing.JTextField cellnumber;
    private javax.swing.JTextField cellwing;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
