/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class NextPage extends javax.swing.JFrame {

    /**
     * Creates new form NextPage
     */
    public NextPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSentences = new javax.swing.JButton();
        jPunishments = new javax.swing.JButton();
        jCells = new javax.swing.JButton();
        jRisks = new javax.swing.JButton();
        jPrisoners = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         PRISON MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 11, 372, 93));

        jSentences.setBackground(new java.awt.Color(255, 255, 255));
        jSentences.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSentences.setText("SENTENCES");
        jSentences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSentencesActionPerformed(evt);
            }
        });
        jPanel1.add(jSentences, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 395, 146, 60));

        jPunishments.setBackground(new java.awt.Color(255, 255, 255));
        jPunishments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPunishments.setText("PUNISHMENTS");
        jPunishments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPunishmentsActionPerformed(evt);
            }
        });
        jPanel1.add(jPunishments, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 225, 60));

        jCells.setBackground(new java.awt.Color(255, 255, 255));
        jCells.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCells.setText("CELLS");
        jCells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCellsActionPerformed(evt);
            }
        });
        jPanel1.add(jCells, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 191, 125, 60));

        jRisks.setBackground(new java.awt.Color(255, 255, 255));
        jRisks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRisks.setText("RISKS");
        jRisks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRisksActionPerformed(evt);
            }
        });
        jPanel1.add(jRisks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 125, 60));

        jPrisoners.setBackground(new java.awt.Color(255, 255, 255));
        jPrisoners.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPrisoners.setText("PRISONERS");
        jPrisoners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrisonersActionPerformed(evt);
            }
        });
        jPanel1.add(jPrisoners, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 194, 66));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\alcatraz-wallpapers-31497-7902136.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrisonersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrisonersActionPerformed
        // TODO add your handling code here:
        Prisoners pr=new Prisoners();
        pr.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jPrisonersActionPerformed

    private void jSentencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSentencesActionPerformed
        // TODO add your handling code here:
        Sentences se=new Sentences();
        se.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSentencesActionPerformed

    private void jPunishmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPunishmentsActionPerformed
        // TODO add your handling code here:
        Punishments pn= new Punishments();
        pn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPunishmentsActionPerformed

    private void jCellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCellsActionPerformed
        // TODO add your handling code here:
        Cells cs=new Cells();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCellsActionPerformed

    private void jRisksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRisksActionPerformed
        // TODO add your handling code here:
        Risks rs=new Risks();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRisksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NextPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NextPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NextPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NextPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NextPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCells;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrisoners;
    private javax.swing.JButton jPunishments;
    private javax.swing.JButton jRisks;
    private javax.swing.JButton jSentences;
    // End of variables declaration//GEN-END:variables
}
