/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PrisonerSearch extends javax.swing.JFrame {

    /**
     * Creates new form PrisonerSearch
     */
    public PrisonerSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prisonerid = new javax.swing.JTextField();
        prisonername = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        com = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRISONERS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 117, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PRISONER ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 94, 158, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PRISONER FIRST NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRISONER CATEGORY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 29));

        prisonerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prisoneridActionPerformed(evt);
            }
        });
        jPanel1.add(prisonerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 104, 150, -1));
        jPanel1.add(prisonername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        clean.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clean.setText("CLEAR");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        jPanel1.add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 89, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 89, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("PRISONER SECOND NAME");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 216, 197, -1));
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, -1));

        com.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A", "B", "C", "D", "H", "N", "S", "T" }));
        jPanel1.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p42.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prisoneridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prisoneridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prisoneridActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(prisonerid.getText().trim().isEmpty()){
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql= "select * from prisoners where Prisoner_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,prisonerid.getText());
            ResultSet rs= pstmt.executeQuery();
            
            if(rs.next())
            {
                prisonername.setText(rs.getString("Prisoner_First_Name"));
                sname.setText(rs.getString("Prisoner_Second_Name"));
               com.setSelectedItem(rs.getString("Prisoner_Category"));
            
            }else{
                JOptionPane.showMessageDialog(null,"Record not Found");
            }
            conn.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         if(prisonername.getText(). trim().isEmpty() && sname.getText().trim().isEmpty() && com.getSelectedItem()=="SELECT" && prisonerid.getText().trim().isEmpty())
             {
             JOptionPane.showMessageDialog(null, "Empty");
             }
             else if(prisonername.getText(). trim().isEmpty()){
             JOptionPane.showMessageDialog(null, "Empty");
            }else if(sname.getText().trim().isEmpty() && !sname.getText().matches("^[a-zA-Z]+$")){
                JOptionPane.showMessageDialog(null, "Empty");
            }
            else if(prisonerid.getText().trim().isEmpty()){
                   JOptionPane.showMessageDialog(null, "Empty");
            }
         else
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql="update prisoners set Prisoner_First_Name=?, Prisoner_Second_Name=?,Prisoner_Category=? where Prisoner_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
         
          if(!prisonername.getText().matches("^[a-zA-Z]+$")){
               JOptionPane.showMessageDialog(null, "Enter alphabets");
          }else if(!sname.getText().matches("^[a-zA-Z]+$")){
             JOptionPane.showMessageDialog(null, "Enter alphabets");
         }
          else
          {
               pstmt.setString(1, prisonername.getText());
            pstmt.setString(2, sname.getText());
            if(com.getSelectedItem()=="SELECT")
            {
               com=null;
            }
            if(com.getSelectedItem()=="A")
            {
              com.getSelectedItem();
            }
            if(com.getSelectedItem()=="B")
            {
              com .getSelectedItem();
            }
            if(com.getSelectedItem()=="C")
            {
               com.getSelectedItem();
            }
            if(com.getSelectedItem()=="D")
            {
              com .getSelectedItem();
            }
            
            if(com.getSelectedItem()=="H")
            {
               com.getSelectedItem();
            }
            if(com.getSelectedItem()=="N")
            {
               com.getSelectedItem();
            }
            if(com.getSelectedItem()=="S")
            {
               com.getSelectedItem();
            }
            if(com.getSelectedItem()=="T")
            {
              com.getSelectedItem();
            }
            pstmt.setString(3,com.getSelectedItem().toString());
             pstmt.setString(4,prisonerid.getText());
             pstmt.executeUpdate();
            
            
                 JOptionPane.showMessageDialog(null,"Update Successful");
             
          }
             conn.close();
            
         }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_updateActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:\
        prisonerid.setText("");
        prisonername.setText("");
       sname.setText("");
       com.setSelectedIndex(0);
        
    }//GEN-LAST:event_cleanActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Prisonerdi p=new Prisonerdi();
        p.setVisible(true);
        this.dispose();
                
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrisonerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrisonerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrisonerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrisonerSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrisonerSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clean;
    private javax.swing.JComboBox<String> com;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prisonerid;
    private javax.swing.JTextField prisonername;
    private javax.swing.JButton search;
    private javax.swing.JTextField sname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
