/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Punishments extends javax.swing.JFrame {

    /**
     * Creates new form Punishments
     */
    public Punishments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPunishment_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcell_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jClear = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");
        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PUNISHMENTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 26, 155, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PUNISHMENT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 120, -1, -1));

        jPunishment_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPunishment_idActionPerformed(evt);
            }
        });
        jPanel1.add(jPunishment_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 120, 219, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PUNISHMENT CELL ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 185, -1, -1));

        jcell_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcell_idActionPerformed(evt);
            }
        });
        jPanel1.add(jcell_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 185, 219, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PUNISHMENT START DATE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 247, 211, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PUNISHMENT END DATE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 302, 194, -1));

        jClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jClear.setText("CLEAR");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });
        jPanel1.add(jClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 441, 117, 51));

        jSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSave.setText("SAVE");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 441, 130, 51));

        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 441, 99, 51));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 441, 107, 51));

        date1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 244, 219, -1));

        date2.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 299, 219, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p17.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcell_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcell_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcell_idActionPerformed

    private void jPunishment_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPunishment_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPunishment_idActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        
        if(jPunishment_id.getText().trim().isEmpty() && jcell_id.getText().trim().isEmpty() && date1.getCalendar()==null && date2.getCalendar()==null)
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }else if(jPunishment_id.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(jcell_id.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if( date1.getCalendar()==null)
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(date2.getCalendar()==null ){
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            
            String sql="insert into punishments values(?,?,?,?)";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(1,jPunishment_id.getText());
             pstmt.setString(2,jcell_id.getText());
             pstmt.setString(3, ((JTextField)date1.getDateEditor().getUiComponent()).getText());
         pstmt.setString(4, ((JTextField)date2.getDateEditor().getUiComponent()).getText());
             pstmt.executeUpdate();
              
              
             JOptionPane.showMessageDialog(null, "Insertion Successfull");
             conn.close();
             
            
             
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Duplicate Entry");
            
        }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
         jPunishment_id.setText("");
        jcell_id.setText("");
        date1.setCalendar(null);
        date2.setCalendar(null);
    }//GEN-LAST:event_jClearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NextPage np=new NextPage();
                 np.setVisible(true);
                 np.pack();
                 np.setLocationRelativeTo(null);
                 np.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        PunishmentsDi p=new PunishmentsDi();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punishments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punishments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punishments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punishments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punishments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPunishment_id;
    private javax.swing.JButton jSave;
    private javax.swing.JTextField jcell_id;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables

    private Object getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
