/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Risks extends javax.swing.JFrame {

    /**
     * Creates new form Risks
     */
    public Risks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        risk_id = new javax.swing.JLabel();
        risk_nature = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        hi = new javax.swing.JRadioButton();
        mi = new javax.swing.JRadioButton();
        lw = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RISK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 134, 54));

        risk_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        risk_id.setForeground(new java.awt.Color(255, 255, 255));
        risk_id.setText("RISK ID");
        jPanel1.add(risk_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 99, 36));

        risk_nature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        risk_nature.setForeground(new java.awt.Color(255, 255, 255));
        risk_nature.setText("RISK NATURE");
        jPanel1.add(risk_nature, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 37));

        rid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 141, 182, -1));

        hi.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(hi);
        hi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hi.setForeground(new java.awt.Color(255, 255, 255));
        hi.setText("HIGH");
        jPanel1.add(hi, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 230, -1, -1));

        mi.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(mi);
        mi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mi.setForeground(new java.awt.Color(255, 255, 255));
        mi.setText("MID");
        jPanel1.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 230, -1, -1));

        lw.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(lw);
        lw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lw.setForeground(new java.awt.Color(255, 255, 255));
        lw.setText("LOW");
        jPanel1.add(lw, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 230, -1, -1));

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 98, 48));

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 99, 48));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 97, 48));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p12.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(rid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }else if(rid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }
       
        
        else
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            
            String sql="insert into risk values(?,?)";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(1,rid.getText());
            String type=null;
             if(hi.isSelected())
             {
                 type=hi.getText();
             }
             if(mi.isSelected())
             {
                 type=mi.getText();
             }
             if(lw.isSelected())
             {
                 type=lw.getText();
             }
             pstmt.setString(2,type);
             
             pstmt.executeUpdate();
              
              JOptionPane.showMessageDialog(null,"Insertion Successful","Risk",JOptionPane.PLAIN_MESSAGE);
             
             
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Duplicate Entry");
            
        }
         
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         rid.setText("");
         buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
       NextPage np=new NextPage();
                 np.setVisible(true);
                 np.pack();
                 np.setLocationRelativeTo(null);
                 np.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 this.dispose();
                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Riskdisplay r=new Riskdisplay();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Risks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Risks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Risks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Risks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Risks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton hi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lw;
    private javax.swing.JRadioButton mi;
    private javax.swing.JTextField rid;
    private javax.swing.JLabel risk_id;
    private javax.swing.JLabel risk_nature;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
