/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class SentenceSearch extends javax.swing.JFrame {

    /**
     * Creates new form SentenceSearch
     */
    public SentenceSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prisonerid = new javax.swing.JTextField();
        cellid = new javax.swing.JTextField();
        riskid = new javax.swing.JTextField();
        punishmentid = new javax.swing.JTextField();
        sentencelength = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        back = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("      SENTENCE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 11, 141, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRISONER ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 88, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CELL ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RISK ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PUNISHMENT ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 265, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENTENCE START");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 322, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SENTENCE LENGTH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 377, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REMISSION DAYS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 434, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRISONER RELEASED ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 493, -1, -1));
        jPanel1.add(prisonerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 88, 150, -1));
        jPanel1.add(cellid, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 148, 150, -1));
        jPanel1.add(riskid, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 205, 150, -1));
        jPanel1.add(punishmentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 265, 150, -1));

        sentencelength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentencelengthActionPerformed(evt);
            }
        });
        sentencelength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sentencelengthKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sentencelengthKeyTyped(evt);
            }
        });
        jPanel1.add(sentencelength, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 377, 150, -1));
        jPanel1.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 434, 150, -1));

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 115, -1, 38));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 227, -1, 33));

        clean.setBackground(new java.awt.Color(0, 0, 0));
        clean.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clean.setForeground(new java.awt.Color(255, 255, 255));
        clean.setText("CLEAR");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        jPanel1.add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 325, 89, 32));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 426, 89, 32));

        date1.setBackground(new java.awt.Color(0, 0, 0));
        date1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 325, 150, -1));

        date2.setBackground(new java.awt.Color(0, 0, 0));
        date2.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 490, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\P52.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if(prisonerid.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Empty"); 
        }
       else
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql= "select * from sentence where Prisoner_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,prisonerid.getText());
            ResultSet rs= pstmt.executeQuery();
            
            if(rs.next())
            {
                cellid.setText(rs.getString("Cell_ID"));
                riskid.setText(rs.getString("Risk_ID"));
                punishmentid.setText(rs.getString("Punishment_ID"));
                date1.setDate(rs.getDate("Sentence_Start"));
                sentencelength.setText(rs.getString("Sentence_Length"));
                days.setText(rs.getString("Remission_Days"));
                date2.setDate(rs.getDate("Prisoner_Released"));
                
                
            }else{
                JOptionPane.showMessageDialog(null,"Record not Found");
            }
            conn.close();
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         if(cellid.getText().trim().isEmpty() && riskid.getText().trim().isEmpty() && punishmentid.getText().trim().isEmpty() && date1.getCalendar()==null && sentencelength.getText().trim().isEmpty() && days.getText().trim().isEmpty() && date2.getCalendar()==null )
        {
          JOptionPane.showMessageDialog(null,"Empty");
        }
        else
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            String sql="Update sentence set Sentence_Start=?,Sentence_Length=?,Remission_Days=?,Prisoner_Released=?,Cell_ID=?,Risk_ID=?,Punishment_ID=? where Prisoner_ID=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setString(7, cellid.getText());
             pstmt.setString(6, riskid.getText());
              pstmt.setString(5, punishmentid.getText());
               pstmt.setString(4, ((JTextField)date1.getDateEditor().getUiComponent()).getText());
                pstmt.setString(3, sentencelength.getText());
                 pstmt.setString(2, days.getText());
                  pstmt.setString(1, ((JTextField)date2.getDateEditor().getUiComponent()).getText());
                  pstmt.setString(8,prisonerid.getText());
             pstmt.executeUpdate();
             
                 
             
             JOptionPane.showMessageDialog(null, "Update Successfull");
             
             conn.close();
            
          }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);  
          }
    }//GEN-LAST:event_updateActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
         prisonerid.setText("");
      cellid.setText("");
      riskid.setText("");
      punishmentid.setText("");
      date1.setCalendar(null);
      sentencelength.setText("");
      days.setText("");
      date2.setCalendar(null);
    }//GEN-LAST:event_cleanActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Sentencedisplay s=new Sentencedisplay();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void sentencelengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentencelengthActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sentencelengthActionPerformed

    private void sentencelengthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sentencelengthKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sentencelengthKeyPressed

    private void sentencelengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sentencelengthKeyTyped
        
    }//GEN-LAST:event_sentencelengthKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SentenceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SentenceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SentenceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SentenceSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SentenceSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField cellid;
    private javax.swing.JButton clean;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JTextField days;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField prisonerid;
    private javax.swing.JTextField punishmentid;
    private javax.swing.JTextField riskid;
    private javax.swing.JButton search;
    private javax.swing.JTextField sentencelength;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
