/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author user
 */
public class Sentences extends javax.swing.JFrame {

    /**
     * Creates new form Sentences
     */
    public Sentences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        puid = new javax.swing.JTextField();
        slength = new javax.swing.JTextField();
        sdays = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISON MANAGEMENT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                            SENTENCE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 334, 47));
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 171, -1));
        jPanel1.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 171, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRISONER ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 92, 154, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CELL ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 143, 154, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RISK ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 189, 91, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PUNISHMENT ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 238, 154, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENTENCE START");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 284, 154, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SENTENCE LENGTH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 328, 154, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REMISSION DAYS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 381, 154, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRISONER RELEASED");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 25));
        jPanel1.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 171, -1));
        jPanel1.add(puid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 171, -1));

        slength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                slengthKeyTyped(evt);
            }
        });
        jPanel1.add(slength, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 171, -1));

        sdays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sdaysKeyTyped(evt);
            }
        });
        jPanel1.add(sdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 171, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 98, 53));

        clean.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clean.setText("CLEAR");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        jPanel1.add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 103, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 110, 50));

        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 110, 50));

        date1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 171, -1));

        date2.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 435, 171, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("G:\\NISHA\\prison\\p18.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int n1,n2,rs;
        
        
        if(pid.getText().trim().isEmpty() && cid.getText().trim().isEmpty() && rid.getText().trim().isEmpty() &&  puid.getText().trim().isEmpty() && date1.getCalendar()==null && slength.getText().trim().isEmpty() && sdays.getText().trim().isEmpty() && date2.getCalendar()==null)
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }else if(pid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(cid.getText().trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(rid.getText().trim().isEmpty())
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(puid.getText().trim().isEmpty())
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(date1.getCalendar()==null)
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(slength.getText().trim().isEmpty())
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(sdays.getText().trim().isEmpty())
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        else if(date2.getCalendar()==null)
        {
            
             JOptionPane.showMessageDialog(null, "Empty");
        }
        
        else
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/prison","root","081721998@ling");
            
            String sql="insert into sentence values(?,?,?,?,?,?,?,?)";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString(8,pid.getText());
             pstmt.setString(7,cid.getText());
              pstmt.setString(6,rid.getText());
               pstmt.setString(5,puid.getText());
                pstmt.setString(4, ((JTextField)date1.getDateEditor().getUiComponent()).getText());
                  pstmt.setString(3,slength.getText());
                  pstmt.setString(2,sdays.getText());
                  
                 pstmt.setString(1, ((JTextField)date2.getDateEditor().getUiComponent()).getText());
                   pstmt.executeUpdate();
                    
            
                 JOptionPane.showMessageDialog(null,"Insertion Successful","Sentence",JOptionPane.PLAIN_MESSAGE);
             
             
             conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
        pid.setText("");
        cid.setText("");
       rid.setText("");
       puid.setText("");
       date1.setCalendar(null);
        slength.setText("");
       sdays.setText("");
      date2.setCalendar(null);
    }//GEN-LAST:event_cleanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NextPage np=new NextPage();
                 np.setVisible(true);
                 np.pack();
                 np.setLocationRelativeTo(null);
                 np.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        Sentencedisplay s=new Sentencedisplay();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void slengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_slengthKeyTyped
        // TODO add your handling code here:
        char ch= evt.getKeyChar();
        if(!(Character.isDigit(ch))){
            evt.consume();
        }
    }//GEN-LAST:event_slengthKeyTyped

    private void sdaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdaysKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_sdaysKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sentences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sentences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sentences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sentences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sentences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private javax.swing.JButton clean;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField puid;
    private javax.swing.JTextField rid;
    private javax.swing.JButton save;
    private javax.swing.JTextField sdays;
    private javax.swing.JTextField slength;
    // End of variables declaration//GEN-END:variables
}
